server:
  port: 8082

spring:
  application:
    name: transaction
  datasource:
    url: jdbc:mysql://localhost:3306/Transaction
    username: 'root'
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

